alias vi='vim -N -u NONE -U NONE --noplugin --cmd "filetype indent on"'
alias todo='todo.sh'
alias sed='gsed'
alias ra='rails'
alias ss='ssh'
alias bu='bundle'
alias be='bundle exec'
alias va='vagrant'
alias vsh='vagrant ssh'
alias reload='source ~/.zshrc'

# ls
alias ll='ls -l'
alias la='ls -a'
alias las='ls -la'

# Git
alias g='git'
alias gci='git commit'
alias gss='git status --short'
alias gp='git push'
alias gpf='git push --force-with-lease'
alias gl='git pull'
alias glr='git pull --rebase'
alias gst='git stash'
alias gstp='git stash pop'
alias grpo='git remote prune origin'
