# zshrc

# Load uitily function
autoload -Uz is-at-least

# Config directory
ZSH_DIR="$HOME/.zsh"

# Remove dups from paths
typeset -aU path cdpath fpath manpath

# Add some completions (we need this before compinit)
[ -e /usr/local/share/zsh-completions ] && fpath=(/usr/local/share/zsh-completions $fpath)
[ -e /opt/boxen/homebrew/share/zsh-completions ] && fpath=(/opt/boxen/homebrew/share/zsh-completions $fpath)
#[ -f /opt/boxen/homebrew/share/zsh/site-functions/git-completion.bash ] && source /opt/boxen/homebrew/share/zsh/site-functions/git-completion.bash

[ -e $ZSH_DIR/completions ] && fpath=($ZSH_DIR/completions $fpath)

# The most important feature of zsh
autoload -Uz compinit
compinit

# cdr
if is-at-least 4.3.11; then
  autoload -Uz chpwd_recent_dirs cdr add-zsh-hook
  add-zsh-hook chpwd chpwd_recent_dirs
  zstyle ":chpwd:*" recent-dirs-max 500
  zstyle ":chpwd:*" recent-dirs-defalut true
  zstyle ":completion:*" recent-dirs-insert always
fi

# Boxen
[ -f /opt/boxen/env.sh ] && source /opt/boxen/env.sh

# Zplug
if [[ -f ~/.zplug/zplug ]]; then
  source ~/.zplug/zplug

  zplug "b4b4r07/zplug"
  zplug "zsh-users/zsh-completions"
  zplug "zsh-users/zsh-history-substring-search"
  zplug "tarruda/zsh-autosuggestions"
  zplug "zsh-users/zsh-syntax-highlighting", nice:19
  zplug "mollifier/anyframe"
  zplug "nojhan/liquidprompt"
  zplug "okuramasafumi/zsh-sensible"

  if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
      echo; zplug install
    fi
  fi

  zplug load
fi

for config ($ZSH_DIR/*.zsh) do source $config; done

stty stop undef
stty start undef

# Anyframe
bindkey "^X'" anyframe-widget-cdr
bindkey "^Xh" anyframe-widget-put-history
bindkey "^Xt" anyframe-widget-tmux-attach
bindkey "^Xb" anyframe-widget-checkout-git-branch

bindkey -e

[ -f /usr/local/share/chruby/chruby.sh ] && source /usr/local/share/chruby/chruby.sh
[ -f /usr/local/share/chruby/auto.sh ] && source /usr/local/share/chruby/auto.sh

if [[ -a ~/.zshrc.local ]]; then
  source ~/.zshrc.local
fi

# direnv
eval "$(direnv hook zsh)"

# Reload path to remove dups
path=($path)
