# zshrc

# Load uitily function
autoload -Uz is-at-least

# Config directory
ZSH_DIR="$HOME/.zsh"

# Remove dups from paths
typeset -aU path cdpath fpath manpath

# Add some completions (we need this before compinit)
[ -e /opt/boxen/homebrew/share/zsh-completions ] && fpath=(/opt/boxen/homebrew/share/zsh-completions $fpath)
#[ -f /opt/boxen/homebrew/share/zsh/site-functions/git-completion.bash ] && source /opt/boxen/homebrew/share/zsh/site-functions/git-completion.bash

# The most important feature of zsh
autoload -Uz compinit
compinit

# cdr
if is-at-least 4.3.11; then
  autoload -Uz chpwd_recent_dirs cdr add-zsh-hook
  add-zsh-hook chpwd chpwd_recent_dirs
  zstyle ":chpwd:*" recent-dirs-max 500
  zstyle ":chpwd:*" recent-dirs-defalut true
  zstyle ":completion:*" recent-dirs-insert always
fi

# Boxen
[ -f /opt/boxen/env.sh ] && source /opt/boxen/env.sh

# Antigen
if [[ -f $ZSH_DIR/antigen/antigen.zsh ]]; then
  source $ZSH_DIR/antigen/antigen.zsh

  # antigen use oh-my-zsh

  antigen bundle git
  antigen bundle git-flow
  antigen bundle rails
  antigen bundle chruby
  antigen bundle osx
  antigen bundle go
  antigen bundle zsh-users/zsh-completions src
  antigen bundle zsh-users/zsh-syntax-highlighting
  antigen bundle zsh-users/zsh-history-substring-search
  antigen bundle tarruda/zsh-autosuggestions
  antigen bundle mollifier/anyframe
  antigen bundle nojhan/liquidprompt
  antigen bundle okuramasafumi/zsh-sensible

  antigen apply
fi

for config ($ZSH_DIR/*.zsh) do source $config; done

stty stop undef
stty start undef

# Anyframe
bindkey "^X'" anyframe-widget-cdr
bindkey "^Xh" anyframe-widget-put-history
bindkey "^Xt" anyframe-widget-tmux-attach
bindkey "^Xb" anyframe-widget-checkout-git-branch

if [[ -a ~/.zshrc.local ]]; then
  source ~/.zshrc.local
fi

# direnv
eval "$(direnv hook zsh)"

# Reload path to remove dups
path=($path)
